#!/usr/bin/env python3
#
# Copyright (C) 2020 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# * Move 'api virtual-host' list to 'api-restrict virtual-host' so it
#   is owned by https.py instead of http-api.py

import sys

from vyos.configtree import ConfigTree

if (len(sys.argv) < 2):
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)

old_base = ['service', 'https', 'certificates']
if not config.exists(old_base):
    # Nothing to do
    sys.exit(0)
else:
    new_base = ['certificate']
    config.set(new_base)

    if config.exists(old_base + ['certbot']):
        if config.exists(old_base + ['certbot', 'domain-name']):
            dn = config.return_values(old_base + ['certbot', 'domain-name'])
            for domain in dn:
                config.set(new_base + ['certbot', 'domain-name'],
                           value=domain, replace=False)
        if config.exists(old_base + ['certbot', 'email']):
            email = config.return_value(old_base + ['certbot', 'email'])
            config.set(new_base + ['certbot', 'email'], value=email)

    config.delete(old_base)

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
