#!/usr/bin/env python3

import os
import sys
import signal
import socket
import logging
from dataclasses import dataclass
from dataclasses import field
from dataclasses import asdict
from enum import IntEnum
from pathlib import Path

from google.protobuf.json_format import MessageToDict
from google.protobuf.json_format import ParseDict

from vyos.config import Config
# from vyos import ConfigError

from vyos.proto import vycall_pb2


class Error(IntEnum):
    SUCCESS = vycall_pb2.SUCCESS
    CONFIG_ERROR = vycall_pb2.CONFIG_ERROR
    DAEMON_ERROR = vycall_pb2.DAEMON_ERROR
    BACKGROUND = vycall_pb2.BACKGROUND


@dataclass
class Reply:
    error: Error
    out: str = ''


@dataclass
class Call:
    script_name: str = None
    tag_value: str = None
    arg_value: str = None
    reply: Reply = None

    def set_reply(self, msg: str, err: Error):
        self.reply = Reply(error=err, out=msg)


@dataclass
class Session:
    session_id: str = ''
    named_active: str = None
    named_proposed: str = None
    dry_run: bool = False
    atomic: bool = False
    background: bool = False
    config: Config = None
    calls: list[Call] = field(default_factory=list)


debug = True

logger = logging.getLogger(__name__)
logs_handler = logging.StreamHandler()
logger.addHandler(logs_handler)

if debug:
    logger.setLevel(logging.DEBUG)
else:
    logger.setLevel(logging.INFO)

SOCKET_PATH = '/run/vyos-commitd.sock'


def msg_to_commit_data(msg: vycall_pb2.Commit) -> Session:
    d = MessageToDict(msg, preserving_proto_field_name=True)
    session = Session(**d)
    session.calls = list(map(lambda x: Call(**x), session.calls))
    return session


def commit_data_to_msg(obj: Session) -> vycall_pb2.Commit:
    msg = vycall_pb2.Commit()
    msg = ParseDict(asdict(obj), msg, ignore_unknown_fields=True)
    return msg


def intialization(session: Session) -> Session:
    return session


def read_message(msg: bytes) -> Session:
    """Read message into Session instance"""

    message = vycall_pb2.Commit()
    message.ParseFromString(msg)
    session = msg_to_commit_data(message)

    for i, call in enumerate(session.calls):
        logger.info(call.script_name)
        call.set_reply(f'{i}th script\n', Error.SUCCESS)

    return session


def write_reply(session: Session) -> bytearray:
    """Serialize modified object to bytearray, prepending data length
    header"""

    reply = commit_data_to_msg(session)
    encoded_data = reply.SerializeToString()
    byte_size = reply.ByteSize()
    length_bytes = byte_size.to_bytes(4)
    arr = bytearray(length_bytes)
    arr.extend(encoded_data)

    return arr


def remove_if_exists(f: str):
    try:
        os.unlink(f)
    except FileNotFoundError:
        pass


def sig_handler(_signum, _frame):
    logger.info('stopping server')
    raise KeyboardInterrupt


def run_server():
    logger.info('starting server')
    server_socket = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)

    signal.signal(signal.SIGTERM, sig_handler)
    signal.signal(signal.SIGINT, sig_handler)

    remove_if_exists(SOCKET_PATH)
    server_socket.bind(SOCKET_PATH)
    Path(SOCKET_PATH).chmod(0o775)

    server_socket.listen(2)
    while True:
        try:
            conn, _ = server_socket.accept()
            logger.debug('connection accepted')
            while True:
                # receive size of data
                data_length = conn.recv(4)
                if not data_length:
                    logger.debug('no data')
                    # if no data break
                    break

                length = int.from_bytes(data_length)
                # receive data
                data = conn.recv(length)

                session = read_message(data)
                reply = write_reply(session)
                conn.sendall(reply)

            conn.close()
            logger.debug('connection closed')

        except KeyboardInterrupt:
            break

    server_socket.close()
    sys.exit(0)


if __name__ == '__main__':
    run_server()
