#!/usr/bin/env python3
#
# Copyright (C) 2021 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#

import os
import sys
import time
import socket
import logging
from types import SimpleNamespace

import vyos.cy_netlink as nl

debug = True

logger = logging.getLogger(__name__)
logs_handler = logging.StreamHandler()
logger.addHandler(logs_handler)

if debug:
    logger.setLevel(logging.DEBUG)
else:
    logger.setLevel(logging.INFO)

def first_parse_rtattr(rta: dict, max_enum: int, leng: int) -> dict: 
    sn = SimpleNamespace()
    sn.len = leng
    d = {}

    while nl.rta_ok(rta, sn.len):
        if rta['rta_type'] <= max_enum:
            d['rta_type'] = rta
        rta = nl.rta_next(rta, sn.len)

    return d

def parse_rtattr(buf: bytes, leng: int) -> dict:
    d = {}
    remaining = leng
    while remaining:
        attr = nl.get_rtattr(buf)
        if not nl.rta_ok(attr, remaining):
            print(f"JSE breaking: attr {attr} rta_ok {nl.rta_ok(attr, remaining)}")
            break

        rta_type = attr['rta_type']
        rta_len = attr['rta_len']
        rta_align = nl.rta_align(rta_len)
        d[rta_type] = buf[:rta_align]

        remaining -= rta_align
        buf = buf[rta_align:]
#        leng = remaining

        print(f"JSE remaining: {remaining}")

    return d

def nl_listen():
    #try
    s = socket.socket(socket.AF_NETLINK, socket.SOCK_RAW, socket.NETLINK_ROUTE)
    s.bind((os.getpid(), nl.RTMGRP_LINK))

    w = nl.test_return()
    print(f"JSE test_return has type: {type(w)}")

    while True:
        data: bytes = s.recv(65535)
        # check length ?
        status: int = len(data)

        nlh = nl.get_header(data)
        siz = nl.get_sizeof_header(nlh)
#        nlmsg_hdrlen = nl.get_nlmsg_hdrlen()
        nlmsg_hdrlen = nl.NLMSG_HDRLEN
        print(f"sizeof nlmsg header is {siz}")
        print(f"nlmsg_hdrlen is {nlmsg_hdrlen}")
        print(f"status is {status}")

        while status >= nlmsg_hdrlen:
            print(f"JSE what is nlh in Python ? Type: {type(nlh)}")
            nlmsg_type: int = nlh['nlmsg_type']
            nlmsg_len: int = nlh['nlmsg_len']
            save_len: int = nlmsg_len
            print(f"nlmsg_type: {nlmsg_type}")
            print(f"nlmsg_len: {nlmsg_len}")


#            data = data[16:]
#            data = nl.Nlmsg_Data(data)
            # do things
#            print(f"JSE doing things; data is {data.decode()}")

            ifi_type, ifi_index, ifi_flags, ifi_change = nl.get_ifinfomsg(data[16:])
            print(f"JSE ifi_type: {ifi_type}, ifi_index: {ifi_index}, ifi_flags: {ifi_flags}, ifi_change: {ifi_change}")
#            ifi_flags = nl.get_ifinfomsg_flags(data)
#            print(f"JSE ifi_flags: {ifi_flags}")
            # get iffinfomsg
            # parse ifinfomsg as rtattr ?
            # record ifUp and ifRun
            #
            # get ifaddrmsg
            # parse ifaddrmsg as rtattr ?
            # get addr

#            data = data[16:]
#            data = nl.ifla_rta(data)
#            print(f"after ifla_rta, data is {data.decode()}")

            res = parse_rtattr(data, nlmsg_len)
            for k, v in res.items():
                print(f"key: {k}, value: {v.decode('utf-8', 'ignore')}")
#            print(f"JSE resulting dict: {res}")

#            save_len = save_len - 32

            status -= nl.nlmsg_align(save_len)
            print(f"JSE save_len: {save_len} status: {status}")
            data = data[nl.nlmsg_align(save_len):]
            if len(data) > nlmsg_hdrlen:
                nlh = nl.get_header(data)

def main():
    nl_listen()

if __name__ == '__main__':
    main()
