#!/usr/bin/env python3

import os
import sys
import json
import signal
import socket
import typing
import logging
import tomli
import importlib.util
from dataclasses import dataclass
from dataclasses import fields
from dataclasses import field
from dataclasses import asdict
from enum import IntEnum
from pathlib import Path

from google.protobuf.json_format import MessageToDict
from google.protobuf.json_format import ParseDict

from vyos.defaults import directories
from vyos.utils.boot import boot_configuration_complete
from vyos.configsource import ConfigSourceCache
from vyos.configsource import ConfigSourceError
from vyos.config import Config
# from vyos import ConfigError

from vyos.proto import vycall_pb2


class Error(IntEnum):
    SUCCESS = vycall_pb2.SUCCESS
    CONFIG_ERROR = vycall_pb2.CONFIG_ERROR
    DAEMON_ERROR = vycall_pb2.DAEMON_ERROR
    BACKGROUND = vycall_pb2.BACKGROUND


@dataclass
class Reply:
    error: Error
    out: str = ''


@dataclass
class Call:
    script_name: str = None
    tag_value: str = None
    arg_value: str = None
    reply: Reply = None

    def set_reply(self, msg: str, err: Error):
        self.reply = Reply(error=err, out=msg)


@dataclass
class Session:
    session_id: str = ''
    named_active: str = None
    named_proposed: str = None
    dry_run: bool = False
    atomic: bool = False
    background: bool = False
    config: Config = None
    session_reply: Reply = None
    calls: list[Call] = field(default_factory=list)

    def set_session_reply(self, msg: str, err: Error):
        self.session_reply = Reply(error=err, out=msg)

@dataclass
class ServerConf:
    commitd_socket: str = ''
    session_dir: str = ''
    running_cache: str = ''
    session_cache: str = ''


server_conf = None
SOCKET_PATH = None

debug = True

logger = logging.getLogger(__name__)
logs_handler = logging.StreamHandler()
logger.addHandler(logs_handler)

if debug:
    logger.setLevel(logging.DEBUG)
else:
    logger.setLevel(logging.INFO)


vyos_conf_scripts_dir = directories['conf_mode']
commitd_include_file = os.path.join(directories['data'], 'configd-include.json')


def key_name_from_file_name(f):
    return os.path.splitext(f)[0]


def module_name_from_key(k):
    return k.replace('-', '_')


def path_from_file_name(f):
    return os.path.join(vyos_conf_scripts_dir, f)


with open(commitd_include_file) as f:
    try:
        include = json.load(f)
    except OSError as e:
        logger.critical(f'configd include file error: {e}')
        sys.exit(1)
    except json.JSONDecodeError as e:
        logger.critical(f'JSON load error: {e}')
        sys.exit(1)


# import conf_mode scripts
(_, _, filenames) = next(iter(os.walk(vyos_conf_scripts_dir)))
filenames.sort()

load_filenames = [f for f in filenames if f in include]
imports = [key_name_from_file_name(f) for f in load_filenames]
module_names = [module_name_from_key(k) for k in imports]
paths = [path_from_file_name(f) for f in load_filenames]
to_load = list(zip(module_names, paths))

modules = []

for x in to_load:
    spec = importlib.util.spec_from_file_location(x[0], x[1])
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    modules.append(module)

conf_mode_scripts = dict(zip(imports, modules))


def write_stdout_log(file_name, msg):
    if boot_configuration_complete():
        return
    with open(file_name, 'a') as f:
        f.write(msg)


def msg_to_commit_data(msg: vycall_pb2.Commit) -> Session:
    d = MessageToDict(msg, preserving_proto_field_name=True)
    session = Session(**d)
    session.calls = list(map(lambda x: Call(**x), session.calls))
    return session


def commit_data_to_msg(obj: Session) -> vycall_pb2.Commit:
    msg = vycall_pb2.Commit()
    msg = ParseDict(asdict(obj), msg, ignore_unknown_fields=True)
    return msg


def load_scripts():
    pass


def initialization(session: Session) -> Session:
    global server_conf

    try:
        configsource = ConfigSourceCache(
            running_config_cache=server_conf.running_cache,
            session_config_cache=server_conf.session_cache,
        )
    except ConfigSourceError as e:
        logger.critical(f'Failed to read config caches: {e}')

    config = Config(config_source=configsource)

    dependent_func: dict[str, list[typing.Callable]] = {}
    setattr(config, 'dependent_func', dependent_func)

    scripts_called = []
    setattr(config, 'scripts_called', scripts_called)

    session.config = config

    return session


def run_script(script_name: str, arg_value: str, config: Config) -> Reply:
    return Reply(Error.SUCCESS, 'success')


def process_node_data(session: Session) -> Session:
    return session


def read_message(msg: bytes) -> Session:
    """Read message into Session instance"""

    message = vycall_pb2.Commit()
    message.ParseFromString(msg)
    session = msg_to_commit_data(message)

    session = initialization(session)

    #    for i, call in enumerate(session.calls):
    #        logger.info(call.script_name)
    #        call.set_reply(f'{i}th script\n', Error.SUCCESS)

    return session


def write_reply(session: Session) -> bytearray:
    """Serialize modified object to bytearray, prepending data length
    header"""

    reply = commit_data_to_msg(session)
    encoded_data = reply.SerializeToString()
    byte_size = reply.ByteSize()
    length_bytes = byte_size.to_bytes(4)
    arr = bytearray(length_bytes)
    arr.extend(encoded_data)

    return arr


def load_server_conf() -> ServerConf:
    try:
        conf_file = directories['vyconfd_conf']
        with open(conf_file, 'rb') as f:
            vyconfd_conf = tomli.load(f)

    except Exception as e:
        logger.critical(f'Failed to open the vyconfd.conf file {conf_file}: {e}')
        sys.exit(1)

    app = vyconfd_conf.get('appliance', {})

    conf_data = {
        k: v for k, v in app.items() if k in [_.name for _ in fields(ServerConf)]
    }

    server_conf = ServerConf(**conf_data)

    return server_conf


def remove_if_exists(f: str):
    try:
        os.unlink(f)
    except FileNotFoundError:
        pass


def sig_handler(_signum, _frame):
    logger.info('stopping server')
    raise KeyboardInterrupt


def run_server():
    global server_conf
    global SOCKET_PATH

    logger.info('starting server')

    server_conf = load_server_conf()
    SOCKET_PATH = server_conf.commitd_socket

    server_socket = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)

    signal.signal(signal.SIGTERM, sig_handler)
    signal.signal(signal.SIGINT, sig_handler)

    remove_if_exists(SOCKET_PATH)
    server_socket.bind(SOCKET_PATH)
    Path(SOCKET_PATH).chmod(0o775)

    server_socket.listen(2)
    while True:
        try:
            conn, _ = server_socket.accept()
            logger.debug('connection accepted')
            while True:
                # receive size of data
                data_length = conn.recv(4)
                if not data_length:
                    logger.debug('no data')
                    # if no data break
                    break

                length = int.from_bytes(data_length)
                # receive data
                data = conn.recv(length)

                session = read_message(data)
                reply = write_reply(session)
                conn.sendall(reply)

            conn.close()
            logger.debug('connection closed')

        except KeyboardInterrupt:
            break

    server_socket.close()
    sys.exit(0)


if __name__ == '__main__':
    run_server()
