#!/usr/bin/env python3

import glob
from lxml import etree

def read_node(n, tree, record):
    name = n.get("name")
    node_type = n.tag
    depth = len(tree.getelementpath(n).split('/'))
    if node_type in ("node", "tagNode"):
        record.setdefault(depth, []).append(name)

    children = n.find("children")
    if node_type in ("node", "tagNode"):
        inner_nodes = children.iterfind("*")
        for inner_n in inner_nodes:
            read_node(inner_n, tree, record)

def report_redundancy(fname, record):
    for k, v in record.items():
        for el in set(v):
            num = v.count(el)
            if num > 1:
                print(f'element {el} appears {num} times at depth {k} in {fname}')

def main():
    for fname in glob.glob('build/interface-definitions/*.xml'):
        tree = etree.parse(fname)
        root = tree.getroot()

        record = {}

        for n in root.findall('*'):
            if n.tag == "syntaxVersion":
                continue
            read_node(n, tree, record)

        report_redundancy(fname, record)

if __name__ == '__main__':
    main()
