#!/usr/bin/env python3
#
# override-help: preprocessor for XML interface definitions to interpret
# redundant entries (relative to path) of property <help> as an override
# directive. Must be called before build-command-templates, as the schema
# disallows redundancy.
#
# Copyright (C) VyOS Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#

# Use lxml xpath capability to find multiple elements with tag help
# relative to path; replace and remove to override the value.

import sys
import glob
import logging
from copy import deepcopy
from lxml import etree

debug = True

logger = logging.getLogger(__name__)
logs_handler = logging.StreamHandler()
logger.addHandler(logs_handler)

if debug:
    logger.setLevel(logging.DEBUG)
else:
    logger.setLevel(logging.INFO)


def clear_empty_path(el):
    # on the odd chance of interleaved comments
    tmp = [lst for lst in el if isinstance(lst.tag, str)]
    if not tmp:
        p = el.getparent()
        p.remove(el)
        logger.debug(f'JSE in clear_empty_path: removing from {p.tag}')
        clear_empty_path(p)


def override_element(lst: list):
    """
    Allow multiple override elements; use the final one (in document order).
    """
    if len(lst) < 2:
        logger.debug('passing list of single element to override_element')
        return

    # assemble list of nodes of overriding help, for later removal
    parents = []
    for el in lst[1:]:
        parents.append(el.getparent())

    # replace element with final override
    what = lst[0].getparent().getparent()
    logger.debug(f'parent tag is {what.tag}')
    lst[0].getparent().replace(lst[0], lst[-1])

    # remove all but overridden element
    for el in parents:
        tmp = el.getparent()
        logger.debug(f'JSE removing from {tmp.tag}')
        tmp.remove(el)
        clear_empty_path(tmp)


def merge_remaining(lst: list, elementtree):
    """
    Merge (now) single node containing 'help' with nodes
    of same path and no 'help'.
    """
    for p in lst:
        p = p.split()
        path_str = '/interfaceDefinition/*'
        path_list = []
        for _, v in enumerate(p):
            path_list.append(f'[@name="{v}"]')
        path_str += '/children/*'.join(path_list)
        rp = elementtree.xpath(path_str)
        if len(rp) > 1:
            for el in rp[1:]:
                # in practice there will only be one child of the path,
                # since override_element() has already run
                for child in el:
                    rp[0].append(deepcopy(child))
                tmp = el.getparent()
                tmp.remove(el)
                clear_empty_path(tmp)


def collect_and_override(dir_name):
    # pylint: disable=too-many-locals,c-extension-no-member
    """
    Collect elements with help tag into dictionary indexed by name
    attributes of ancestor path.
    """
    for fname in glob.glob(f'{dir_name}/*.xml'):
        tree = etree.parse(fname)
        root = tree.getroot()
        defv = {}

        xpath_str = '//help'
        xp = tree.xpath(xpath_str)

        for element in xp:
            ap = element.xpath('ancestor::*[@name]')
            ap_name = [el.get('name') for el in ap]
            ap_path_str = ' '.join(ap_name)
            defv.setdefault(ap_path_str, []).append(element)

        trivial = []
        for k, v in defv.items():
            if len(v) < 2:
                trivial.append(k)
        for i in trivial:
            del defv[i]

        for k, v in defv.items():
            logger.debug(f'JSE in {fname}: path is \'{k}\'')
            for i in v:
                logger.debug(f'element is {i.tag} {i.text}')

        continue

        for k, v in defv.items():
            if len(v) > 1:
                logger.info(f"overriding help in {fname} at path '{k}'")
                override_element(v)

        to_merge = list(defv)
        merge_remaining(to_merge, tree)

        revised_str = etree.tostring(root, encoding='unicode', pretty_print=True)

        with open(f'{fname}', 'w') as f:
            f.write(revised_str)


def main():
    if len(sys.argv) < 2:
        logger.critical('Must specify XML directory!')
        sys.exit(1)

    dir_name = sys.argv[1]

    collect_and_override(dir_name)


if __name__ == '__main__':
    main()
